// js function to enable textbox by checkbox generated by for loop

 function chkBox(enable, amount_id, remarks_id) {
    console.log(enable);
    console.log(amount_id);
    console.log(remarks_id);
    document.getElementById(amount_id).disabled = !enable;
    document.getElementById(remarks_id).disabled = !enable;
}

// view

@forelse ($claims as $key => $item)
    <tr data-id="{{$item->id}}">
        <td>
            <input type="checkbox" class="checkbox" name="salhead[]" value="{{$item->id}}" onclick="chkBox(this.checked, 'amount_{{$item->id}}', 'remarks_{{$item->id}}')"/>    
        </td>
        <td>{{ $item->name }}</td>
        <td>{{ $item->code }}</td>
        <td>
            <input type="text" class="form-control" id="amount_{{$item->id}}" name="amount_{{$item->id}}" value=0.00 disabled="disabled">
        </td>
        <td>
            <input type="text" class="form-control" id="remarks_{{$item->id}}" name="remarks_{{$item->id}}" placeholder="Remarks" disabled="disabled"/>
        </td>
    </tr>
@empty
    <tr>
        <td class="text-danger text-center" colspan="5">Claims head not found.</td>
    </tr>
@endforelse